apiVersion: batch/v1
kind: Job
metadata:
  name: nsc
spec:
  template:
    affinity:
     nodeAffinity:
       requiredDuringSchedulingIgnoredDuringExecution:
         nodeSelectorTerms:
         - matchExpressions:
           - key: nvidia.com/gpu.product
             operator: In
             values:
             - NVIDIA-GeForce-RTX-3090
    containers:
      - name: nsc
        image: vedavamadathil/nsc:latest
        command:
          - sh
          - -c
          - "cd /opt/repo/nsc && pip install -r requirements.txt && sh setup.sh"
        resources:
          requests:
            memory: 16Gi
            cpu: 8
            nvidia.com/gpu: 1
          limits:
            memory: 16Gi
            cpu: 8
            nvidia.com/gpu: 1
        volumeMounts:
              - name: git-repo
                mountPath: /opt/repo
    initContainers:
      - name: init-clone-repo
        image: alpine/git
        args:
          - clone
          - https://github.com/vedavamadathil/nsc
          - /opt/repo/nsc
        volumeMounts:
          - name: git-repo
            mountPath: /opt/repo
    volumes:
        - name: git-repo
          emptyDir: {}
    restartPolicy: Never
